### ISSUE TITLE
Download der Bilder funktioniert nicht

### ISSUE THREAD

**Issue by mkonline** [terminal42/contao-bynder#12]
Ich habe jetzt auf verschiedene Contao-Versionen (4.9 und 4.10) versucht, das Module zum laufen zu überreden, leider ohne Erfolg.
Die Liste der Datei wird angezeigt, die Filteroptionen werden auch geladen, wenn ich auf den Download klicke, bekomme ich nach kurzer Zeit in der JS-Console eine Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/46937345/104132002-c455b980-537a-11eb-9ecf-53904a65d02a.png)

Request: http://contao.domain/_bynder_api/download?mediaId=64A5335C-1E06-48AD-8C46E2B289EEB80A
Antwort:
{"status":"FAILED","uuid":null}

Wenn ich mich bei Bynder einlogge,  bekomme ich die Informationen angezeigt.
Einen Hinweis habe ich noch, bei der Beschreibung fehlt die baseUrl, diese muss gesetzt werde und bei der Installation über den Contao-Manager muss die config.conf vor der Installation geändert werden.

Mein config.yml sieht so aus:

`terminal42_contao_bynder:
    baseUrl: 'https://mybynder.domain.de/'
    consumerKey: '0815ABC-XXXX-XXXX-XXXXXXXXXXXXXXX'
    consumerSecret: 'f30b378c95c804b3ac8fa0f754f7a226'
    token: 'APITOKEN-XXXX-XXXX-XXXXXXXXXXXXXXX
    tokenSecret: 'zmktrg4mjro3s4am57e7e827vtq'
    targetDir: 'bynder_assets' 
    derivativeName: 'Print' #
    derivativeOptions:
        w: 3000
        h: 3000
        crop: false      `

**Comment by Toflar** [comment]
Die Fehlermeldung und das Logging wurden in der letzten Bugfix-Version verbessert, evtl. sagen dir dann die Einträge in var/logs mehr. Aber ansonsten läuft die Extension sicher, sie wird bei uns jeden Tag genutzt :)
